### ISSUE TITLE
no usage description

### ISSUE THREAD

**Issue by saurabh1234** [pda/devise-login-cookie#1]
Hii...can u provide how to use the gem please.....
Thanks

**Comment by pda** [comment]
Sure - I'll try and find time to update the docs.
In the mean time, here's roughly what I've got:

**Gemfile**

```
gem "devise-login-cookie", "~> 0.1"
```

**config/initializers/devise.rb**

```
Devise.setup do |config|

  # ... after all the usual stuff

  require 'devise-login-cookie'

  # Add the devise-login-cookie gem as a strategy for Single Sign On.
  config.warden do |manager|
    manager.default_strategies(:scope => :user) << :devise_login_cookie
  end

end
```

This causes Devise and Warden to set a `login_user_token` signed cookie containing the userid and the time the cookie was created.  The presence of this cookie on subsequent requests will log in a user if they are not logged in.

Integrating the same behaviour into another application (which is the whole idea of it, as a Single Sign On) is another matter.  I'm planning on getting the PHP and Python versions of the `signed_json` implementation open sourced early in the new year.

Cheers,
Paul
