### ISSUE TITLE
Please update for Devise 2.1.2

### ISSUE THREAD

**Issue by edwinramirez** [pda/devise-login-cookie#2]
I'm developing an API to manage authentication using devise but I need to manage a cookie containing the necessary auth info. Your gem looks like the answer I was looking for but it looks like it requires an old version of devise.

Here is the output after running "bundle install" trying to include your gem.
Bundler could not find compatible versions for gem "devise":

```
In Gemfile:
devise-login-cookie (>= 0) ruby depends on
devise (~> 1.1.0) ruby
devise (2.1.2)
```

If you could update this gem it would be great. Although I imagine it wouldn't be a short and easy task.

**Comment by pda** [comment]
I'm afraid I'm not going to have time (or reason) to get this updated, but pull requests are welcome.
Cheers, Paul.
